version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignoring these dependencies temporarily for compatibility
      - dependency-name: "numpy"
      - dependency-name: "pandas"
    labels:
        - "pip-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      labels:
        - "actions"