name: GridTradingBot
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.11
  - pandas=1.5.3
  - numpy=1.23.4
  - plotly=5.11.0
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - tabulate=0.9.0
  - pip
  - pip:
    - ccxt
    - configparser