name: GridTradingBot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - plotly
  - pytest
  - pytest-asyncio
  - pytest-cov
  - tabulate
  - pip
  - pip:
    - apprise
    - ccxt
    - configparser
    - psutil
    - python-dotenv