name: GridTradingBot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pandas=2.2.3
  - numpy=2.1.3
  - plotly=5.24.1
  - pytest=8.3.3
  - pytest-asyncio=0.24.0
  - pytest-cov=6.0.0
  - tabulate=0.9.0
  - pip=24.3.1
  - pip:
    - apprise==1.9.0
    - ccxt==4.4.29
    - configparser==7.1.0
    - psutil==6.1.0
    - python-dotenv==1.0.1
