server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: bot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: grid_trading_bot
          __path__: /logs/**/*.log
    pipeline_stages:
      # Extract detailed info from filename
      - regex:
          source: filename
          expression: 'bot_(?P<base>[A-Z]+)_(?P<quote>[A-Z]+)_(?P<mode>[A-Z]+)_strategy(?P<strategy>[A-Z_]+)_spacing(?P<spacing>[A-Z]+)_size(?P<size>\d+)_range(?P<range>\d+-\d+)_.*\.log'
      - labels:
          base_currency: '{{ .base }}'
          quote_currency: '{{ .quote }}'
          trading_mode: '{{ .mode }}'
          strategy_type: '{{ .strategy }}'
          spacing_type: '{{ .spacing }}'
          grid_size: '{{ .size }}'
          grid_range: '{{ .range }}'
      
      # Extract ticker price from log lines
      - regex:
          expression: '^(?P<timestamp>\S+ \S+),\d+ - (?P<service>\S+) - (?P<level>\S+) - Connected to WebSocket for (?P<trading_pair>\S+USDT) ticker current price: (?P<current_price>\d+\.\d+)'
      - labels:
          timestamp: '{{ .timestamp }}'
          service: '{{ .service }}'
          level: '{{ .level }}'
          trading_pair: '{{ .trading_pair }}'
          current_price: '{{ .current_price }}'

      # Regex for other types of logs (non-WebSocket related)
      - regex:
          source: message
          expression: '^(?P<timestamp>\S+ \S+),(?P<ms>\d+) - (?P<service>\S+) - (?P<level>\S+) - .+'
      - labels:
          timestamp: '{{ .timestamp }} {{ .ms }}'
          service: '{{ .service }}'
          level: '{{ .level }}'
      
      # Fallback regex to capture any other log lines that don't match the above patterns
      - regex:
          source: message
          expression: '.+'
      - labels:
          default: 'true'
      
      # Output stage: Pass timestamp as the source
      - output:
          source: message
          format: '{{ .timestamp }} - {{ .level }} - {{ .message }}'