groups:
    - name: grid_trading_alerts
      rules:
        - alert: HighCPUUsage
          expr: |
            avg_over_time({job="grid_trading_bot"} | json | unwrap cpu [5m]) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: High CPU usage detected
        - alert: OrderExecutionFailure
          expr: |
            count_over_time({job="grid_trading_bot"} |= "Failed to execute order" [5m]) > 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Multiple order execution failures detected
