name: on_push_or_merge_pr_master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: goanpeca/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12

    - name: Create or update Conda environment
      shell: bash -l {0}
      run: |
        conda env create --file environment.yml --name GridTradingBot || conda env update --file environment.yml --name GridTradingBot

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
    
    - name: Run tests and upload coverage
      run: |
        conda run -n GridTradingBot python -m pip install --upgrade pip
        conda run -n GridTradingBot pytest --cov=core --cov=config --cov=strategies --cov=utils --cov-report=xml --cov-report=term
      continue-on-error: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
