name: on_push_or_merge_pr_master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Miniconda
      uses: goanpeca/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11

    - name: Create or update Conda environment
      shell: bash -l {0}
      run: |
        conda env create --file environment.yml --name GridTradingBot || conda env update --file environment.yml --name GridTradingBot

    - name: Activate Conda environment and run tests
      run: |
        conda run -n GridTradingBot python -m pip install --upgrade pip  # Update pip inside the Conda environment
        conda run -n GridTradingBot pytest --cov=core  # Run tests using pytest

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml